<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IncidentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('incident')->insert([
            ['type' => 'Ambulance Assistance', 'assistance_id' => 1],
            ['type' => 'Attempted Suicide', 'assistance_id' => 1],
            ['type' => 'Drowning', 'assistance_id' => 1],
            ['type' => 'Electrocution', 'assistance_id' => 1],
            ['type' => 'Found Wounded Person', 'assistance_id' => 1],
            ['type' => 'Hit and Run – Traffic Accident', 'assistance_id' => 1],
            ['type' => 'Mentally-ill Person', 'assistance_id' => 1],
            ['type' => 'Threatened Abortion', 'assistance_id' => 1],
            ['type' => 'Vehicular Accident/Collision', 'assistance_id' => 1],

            ['type' => 'Abandoned Child', 'assistance_id' => 2],
            ['type' => 'Abortion', 'assistance_id' => 2],
            ['type' => 'Act of Lasciviousness', 'assistance_id' => 2],
            ['type' => 'Amok', 'assistance_id' => 2],
            ['type' => 'Anti-Fencing', 'assistance_id' => 2],
            ['type' => 'Bank Robbery', 'assistance_id' => 2],
            ['type' => 'Battered Wife', 'assistance_id' => 2],
            ['type' => 'Bomb Threat', 'assistance_id' => 2],
            ['type' => 'Bombing Incident', 'assistance_id' => 2],
            ['type' => 'Burglary', 'assistance_id' => 2],
            ['type' => 'Carnapping', 'assistance_id' => 2],
            ['type' => 'Child Abuse', 'assistance_id' => 2],
            ['type' => 'Coercion', 'assistance_id' => 2],
            ['type' => 'Creating Trouble', 'assistance_id' => 2],
            ['type' => 'Domestic Trouble', 'assistance_id' => 2],
            ['type' => 'Estafa/Swindling', 'assistance_id' => 2],
            ['type' => 'Extortion (LAW ENF)', 'assistance_id' => 2],
            ['type' => 'Extortion (LCE)', 'assistance_id' => 2],
            ['type' => 'Found Dead Person', 'assistance_id' => 2],
            ['type' => 'Found Explosive Devices', 'assistance_id' => 2],
            ['type' => 'Grave Threat', 'assistance_id' => 2],
            ['type' => 'Gun Poking', 'assistance_id' => 2],
            ['type' => 'Gun Toting', 'assistance_id' => 2],
            ['type' => 'Hacking', 'assistance_id' => 2],
            ['type' => 'Harassment', 'assistance_id' => 2],
            ['type' => 'Hazing', 'assistance_id' => 2],
            ['type' => 'Highway Robbery', 'assistance_id' => 2],
            ['type' => 'Hijacking', 'assistance_id' => 2],
            ['type' => 'Hostage Taking', 'assistance_id' => 2],
            ['type' => 'Illegal Arrest (LCE)', 'assistance_id' => 2],
            ['type' => 'Illegal Detention (LAW ENF)', 'assistance_id' => 2],
            ['type' => 'Illegal Possession of Firearms', 'assistance_id' => 2],
            ['type' => 'Indecent Shows', 'assistance_id' => 2],
            ['type' => 'Indiscriminate Firing', 'assistance_id' => 2],
            ['type' => 'Kidnapping/Abduction', 'assistance_id' => 2],
            ['type' => 'Maltreatment', 'assistance_id' => 2],
            ['type' => 'Mauling', 'assistance_id' => 2],
            ['type' => 'Murder/Homicide', 'assistance_id' => 2],
            ['type' => 'Oral Defamation', 'assistance_id' => 2],
            ['type' => 'Physical Injury', 'assistance_id' => 2],
            ['type' => 'Piracy', 'assistance_id' => 2],
            ['type' => 'Prostitution', 'assistance_id' => 2],
            ['type' => 'Rape', 'assistance_id' => 2],
            ['type' => 'Riot', 'assistance_id' => 2],
            ['type' => 'Robbery', 'assistance_id' => 2],
            ['type' => 'Rumble', 'assistance_id' => 2],
            ['type' => 'Sexual Harassment', 'assistance_id' => 2],
            ['type' => 'Shooting Incident', 'assistance_id' => 2],
            ['type' => 'Stabbing', 'assistance_id' => 2],
            ['type' => 'Suicide', 'assistance_id' => 2],
            ['type' => 'Suspicious Person', 'assistance_id' => 2],
            ['type' => 'Suspicious Vehicle', 'assistance_id' => 2],
            ['type' => 'Theft', 'assistance_id' => 2],
            ['type' => 'Unjust Vexation', 'assistance_id' => 2],

            ['type' => 'Burning Garbage', 'assistance_id' => 3],
            ['type' => 'Burning Hazardous Material', 'assistance_id' => 3],
            ['type' => 'Busted Transformer', 'assistance_id' => 3],
            ['type' => 'Chemical Fire', 'assistance_id' => 3],
            ['type' => 'Commercial Fire', 'assistance_id' => 3],
            ['type' => 'Electrical Fire', 'assistance_id' => 3],
            ['type' => 'Factory Fire', 'assistance_id' => 3],
            ['type' => 'Forest Fire', 'assistance_id' => 3],
            ['type' => 'Gas Leak (LPG, Acetelyn etc.)', 'assistance_id' => 3],
            ['type' => 'Grass Fire', 'assistance_id' => 3],
            ['type' => 'Industrial Fire', 'assistance_id' => 3],
            ['type' => 'Open Live Wire', 'assistance_id' => 3],
            ['type' => 'Post Fire', 'assistance_id' => 3],
            ['type' => 'Residential Fire', 'assistance_id' => 3],
            ['type' => 'Ship / Vessel Fire', 'assistance_id' => 3],
            ['type' => 'Structural Fire', 'assistance_id' => 3],
            ['type' => 'Vehicular Fire', 'assistance_id' => 3],

            ['type' => 'Earthquake', 'assistance_id' => 4],
            ['type' => 'Flood', 'assistance_id' => 4],
            ['type' => 'Landslide', 'assistance_id' => 4],
            ['type' => 'Missing Person', 'assistance_id' => 4],
            ['type' => 'Rescue', 'assistance_id' => 4],
            ['type' => 'Sinking Water Vessel / Ship', 'assistance_id' => 4],
            ['type' => 'Typhoon', 'assistance_id' => 4],
            ['type' => 'Volcanic Eruption', 'assistance_id' => 4],

            ['type' => 'Abandoned Vehicle', 'assistance_id' => 5],
            ['type' => 'Abuse of Authority', 'assistance_id' => 5],
            ['type' => 'Abusive Driver', 'assistance_id' => 5],
            ['type' => 'Barangay Assistance', 'assistance_id' => 5],
            ['type' => 'Bingo', 'assistance_id' => 5],
            ['type' => 'Busted Pipes', 'assistance_id' => 5],
            ['type' => 'Cara Y Cruz', 'assistance_id' => 5],
            ['type' => 'Color Games', 'assistance_id' => 5],
            ['type' => 'Damage to Property', 'assistance_id' => 5],
            ['type' => 'Defective Drainage', 'assistance_id' => 5],
            ['type' => 'Demolition', 'assistance_id' => 5],
            ['type' => 'Drinking in Public Place', 'assistance_id' => 5],
            ['type' => 'Drag Racing', 'assistance_id' => 5],
            ['type' => 'Drug Den', 'assistance_id' => 5],
            ['type' => 'Drug Possession', 'assistance_id' => 5],
            ['type' => 'Drug Pusher/Pushing', 'assistance_id' => 5],
            ['type' => 'Drug Trafficking', 'assistance_id' => 5],
            ['type' => 'Drug User', 'assistance_id' => 5],
            ['type' => 'Dumping Hazardous Material - L', 'assistance_id' => 5],
            ['type' => 'Dumping Hazardous Material - S', 'assistance_id' => 5],
            ['type' => 'Fallen Post', 'assistance_id' => 5],
            ['type' => 'Fallen Tree', 'assistance_id' => 5],
            ['type' => 'Family Quarrel', 'assistance_id' => 5],
            ['type' => 'Fruit Games', 'assistance_id' => 5],
            ['type' => 'Horse Racing', 'assistance_id' => 5],
            ['type' => 'Illegal Construction', 'assistance_id' => 5],
            ['type' => 'Illegal Drug Manufacturing', 'assistance_id' => 5],
            ['type' => 'Illegal Electrical Connections', 'assistance_id' => 5],
            ['type' => 'Illegal Gambling', 'assistance_id' => 5],
            ['type' => 'Illegal Logging', 'assistance_id' => 5],
            ['type' => 'Illegal MFG of Explosives', 'assistance_id' => 5],
            ['type' => 'Illegal Parking', 'assistance_id' => 5],
            ['type' => 'Illegal Recruitment', 'assistance_id' => 5],
            ['type' => 'Illegal Sidewalk Vendors', 'assistance_id' => 5],
            ['type' => 'Illegal TV Cable Connection', 'assistance_id' => 5],
            ['type' => 'Illegal Water Connection', 'assistance_id' => 5],
            ['type' => 'Jai Alai', 'assistance_id' => 5],
            ['type' => 'Jueteng', 'assistance_id' => 5],
            ['type' => 'Mahjong', 'assistance_id' => 5],
            ['type' => 'Marijuana Cultivation', 'assistance_id' => 5],
            ['type' => 'Neighbor Quarrel', 'assistance_id' => 5],
            ['type' => 'Nuisance', 'assistance_id' => 5],
            ['type' => 'Open Man-hole', 'assistance_id' => 5],
            ['type' => 'POT Session', 'assistance_id' => 5],
            ['type' => 'Pula at Puti', 'assistance_id' => 5],
            ['type' => 'Reckless Driving', 'assistance_id' => 5],
            ['type' => 'Rugby Boys', 'assistance_id' => 5],
            ['type' => 'Sakla', 'assistance_id' => 5],
            ['type' => 'Shoplifting', 'assistance_id' => 5],
            ['type' => 'Smoke Belching', 'assistance_id' => 5],
            ['type' => 'Smuggling', 'assistance_id' => 5],
            ['type' => 'Snatching/Slashing', 'assistance_id' => 5],
            ['type' => 'Squatting', 'assistance_id' => 5],
            ['type' => 'Stalled Vehicle', 'assistance_id' => 5],
            ['type' => 'Stoning Incident', 'assistance_id' => 5],
            ['type' => 'Street Children', 'assistance_id' => 5],
            ['type' => 'Tampered Plate Number', 'assistance_id' => 5],
            ['type' => 'Tampered Taxi Meter', 'assistance_id' => 5],
            ['type' => 'Tampered Utility Meters', 'assistance_id' => 5],
            ['type' => 'Tong-its', 'assistance_id' => 5],
            ['type' => 'Traffic Problem', 'assistance_id' => 5],
            ['type' => 'Trespassing', 'assistance_id' => 5],
            ['type' => 'Trip Cutting', 'assistance_id' => 5],
            ['type' => 'Tupada/Sabong', 'assistance_id' => 5],
            ['type' => 'Uncollected Garbage', 'assistance_id' => 5],
            ['type' => 'Unfair Trade Practice', 'assistance_id' => 5],
            ['type' => 'Video Games', 'assistance_id' => 5],
            ['type' => 'Video Karera', 'assistance_id' => 5],
            ['type' => 'Wanted Person', 'assistance_id' => 5],

            ['type' => 'Others', 'assistance_id' => 6]
        ]);
    }
}
